1.update install docker on windows

diff --git a/.github/actions/service/oracle/action.yml b/.github/actions/service/oracle/action.yml
--- a/.github/actions/service/oracle/action.yml
+++ b/.github/actions/service/oracle/action.yml
@@ -39,9 +39,36 @@ runs:
                   fi
                 done
               done
+#        - if: runner.os == 'Windows'
+#          name: Start Oracle container
+#          shell: wsl-run {0}
+#          run: |
+#              for port in ${{ inputs.ports }}; do
+#                 docker run -d --name "${{ inputs.version }}-$port" -p $port:1521 -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=Oracle123 container-registry.oracle.com/database/free:23.5.0.0-lite
+#              done
+#        - if: runner.os == 'Windows'
+#          name: Verify Oracle Database is running
+#          id: oracleContainerWin
+#          shell: wsl-run {0}
+#          run: |
+#              docker ps
+#              sleep 10
+#              for port in ${{ inputs.ports }}; do
+#                while true; do
+#                log_output=$(docker logs "${{ inputs.version }}-$port" 2>&1 | grep -i "DATABASE IS READY TO USE" || true)
+#                if [ -z "$log_output" ]; then
+#                  echo "'XDB initialized' not found in the logs, retrying in 100 seconds..."
+#                  docker logs --tail 10 ${{ inputs.version }}-$port
+#                  sleep 30
+#                else
+#                  echo "'XDB initialized.' found in the logs, continuing."
+#                  break
+#                fi
+#                done
+#              done
         - if: runner.os == 'Windows'
           name: Start Oracle container
-          shell: wsl-run {0}
+          shell: cmd
           run: |
               for port in ${{ inputs.ports }}; do
                  docker run -d --name "${{ inputs.version }}-$port" -p $port:1521 -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=Oracle123 container-registry.oracle.com/database/free:23.5.0.0-lite                
@@ -49,7 +76,7 @@ runs:
         - if: runner.os == 'Windows'
           name: Verify Oracle Database is running
           id: oracleContainerWin
-          shell: wsl-run {0}
+          shell: cmd
           run: |
               docker ps
               sleep 10
@@ -57,11 +84,11 @@ runs:
                 while true; do
                 log_output=$(docker logs "${{ inputs.version }}-$port" 2>&1 | grep -i "DATABASE IS READY TO USE" || true)
                 if [ -z "$log_output" ]; then
-                  echo "'XDB initialized' not found in the logs, retrying in 100 seconds..."
+                  echo "orcle not stated , waitting 10 seconds..."
                   docker logs --tail 10 ${{ inputs.version }}-$port
-                  sleep 30
+                  sleep 10
                 else
-                  echo "'XDB initialized.' found in the logs, continuing."
+                  echo "orcle already stated."
                   break
                 fi
                 done
